#Falta fazer

CC = g++
LD = g++

CFLAGS = -Wall
LFLAGS = -Wall

TRAB1OBJS = 

TRABALHOS = ./trab1.exe

.cpp.o:
		$(CC) $(CFLAGS) -c $<

all: $(TRABALHOS)

trab1: $(TRAB1OBJS)
		$() $() -o $@ $() -lm

clean:
		rm $(TRABALHOS)
		
#*.exe
#o $(TRABALHOS)